In [3]:
import torch

In [4]:
# torch 버전 확인
print(torch.__version__)

2.4.0


In [5]:
# gpu 사용 가능 여부 확인
torch.backends.mps.is_available()

True

In [6]:
t = torch.FloatTensor([0., 1., 3., 4., 5., 6.,])
print(t)

tensor([0., 1., 3., 4., 5., 6.])


In [7]:
print(t.dim()) # rank = 차원
print(t.shape) # shape
print(t.size()) # shape

1
torch.Size([6])
torch.Size([6])


In [8]:
print(t[0], t[1], t[-1]) # 인덱스로 접근
print(t[2:5], t[4:-1]) # 슬라이싱
print(t[:2], t[3:]) # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([3., 4., 5.]) tensor([5.])
tensor([0., 1.]) tensor([4., 5., 6.])


In [9]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [10]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [11]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [12]:
print(t.max()) # Returns one value: max


tensor(4.)


In [13]:
print(t.max(dim=0)) # Returns two values: max and argmax

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [14]:
# 10개 사물 분류 모델
result = torch.FloatTensor([0.1, 0.04, 0.1, 0.1, 0.01, 0.01, 0.01, 0.01, 0.89])
names = ['cat', 'dog', 'lion', 'tiger', 'wolf', 'fox', 'rabbit', 'snake', 'zebra',  'horse']
names[result.argmax()]

'zebra'

## View()

In [15]:
import numpy as np

t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
ft.shape


torch.Size([2, 2, 3])

In [16]:
reshaped_ft = ft.view([3, 4])
reshaped_ft.shape

torch.Size([3, 4])

In [17]:
reshaped_ft = ft.view([4, 3])
reshaped_ft.shape

torch.Size([4, 3])

In [18]:
reshaped_ft = ft.view([2, -1])
reshaped_ft.shape

torch.Size([2, 6])

In [19]:
reshaped_ft = ft.view([4, 3, 1])
reshaped_ft.shape

torch.Size([4, 3, 1])

## Sqeeze & Unsqeeze

In [20]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [21]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [22]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

tensor([[[0.],
         [1.],
         [2.]]])
torch.Size([1, 3, 1])


# 파이토치로 선형 회귀 구현하기

In [23]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [24]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [25]:
x_train.shape

torch.Size([3, 1])

In [26]:
y_train.shape

torch.Size([3, 1])

In [27]:
W = torch.zeros(1, requires_grad=True) # requires_grad = True로 설정해줘야 가중치가 바뀜, 학습이 가능

In [28]:
b = torch.zeros(1, requires_grad=True)

In [29]:
y_pred = x_train * W + b

In [30]:
loss = torch.mean((y_train - y_pred) ** 2)
loss

tensor(18.6667, grad_fn=<MeanBackward0>)

In [31]:
optimizer = torch.optim.SGD([W, b], lr=0.001)

In [32]:
optimizer.zero_grad() # 다음 계산을 위한 가중치 초기화

loss.backward()

optimizer.step() # 파라미터 값[W, b] 수정

In [33]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 30 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

	# H(x) 계산
	hypothesis = x_train * W + b

	# cost 계산
	cost = torch.mean((hypothesis - y_train) ** 2)

	# cost로 H(x) 개선
	optimizer.zero_grad()
	cost.backward()
	optimizer.step()

	# 100번마다 로그 출력
	# if epoch % 100 == 0:
	print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
		epoch, nb_epochs, W.item(), b.item(), cost.item()
	))


Epoch    0/30 W: 0.187, b: 0.080 Cost: 18.666666
Epoch    1/30 W: 0.353, b: 0.151 Cost: 14.770963
Epoch    2/30 W: 0.500, b: 0.214 Cost: 11.691541
Epoch    3/30 W: 0.632, b: 0.270 Cost: 9.257346
Epoch    4/30 W: 0.749, b: 0.319 Cost: 7.333169
Epoch    5/30 W: 0.853, b: 0.363 Cost: 5.812135
Epoch    6/30 W: 0.945, b: 0.401 Cost: 4.609764
Epoch    7/30 W: 1.028, b: 0.435 Cost: 3.659278
Epoch    8/30 W: 1.101, b: 0.466 Cost: 2.907896
Epoch    9/30 W: 1.166, b: 0.492 Cost: 2.313895
Epoch   10/30 W: 1.224, b: 0.516 Cost: 1.844294
Epoch   11/30 W: 1.276, b: 0.536 Cost: 1.473027
Epoch   12/30 W: 1.322, b: 0.555 Cost: 1.179487
Epoch   13/30 W: 1.363, b: 0.571 Cost: 0.947386
Epoch   14/30 W: 1.400, b: 0.585 Cost: 0.763851
Epoch   15/30 W: 1.433, b: 0.597 Cost: 0.618704
Epoch   16/30 W: 1.462, b: 0.608 Cost: 0.503902
Epoch   17/30 W: 1.488, b: 0.617 Cost: 0.413086
Epoch   18/30 W: 1.511, b: 0.625 Cost: 0.341229
Epoch   19/30 W: 1.531, b: 0.632 Cost: 0.284360
Epoch   20/30 W: 1.550, b: 0.638 Cost

# nn.Module과 클래스로 구현하기

In [34]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [35]:
torch.manual_seed(1)

In [36]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
							
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])


In [37]:
model = nn.Linear(3, 1) # parameter = input * output + 1(bias)
list(model.parameters())

[Parameter containing:
 tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True),
 Parameter containing:
 tensor([0.2710], requires_grad=True)]

In [38]:
optimizer = optim.SGD(model.parameters(), lr=1e-5)

epochs = 100

for epoch in range(epochs):

	# H(x) 계산
	prediction = model(x_train)
	# model(x_train)은 model.forward(x_train)와 동일함.

	# cost 계산
	cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

	# cost로 H(x) 개선하는 부분
	# gradient를 0으로 초기화
	optimizer.zero_grad()
	# 비용 함수를 미분하여 gradient 계산
	cost.backward()
	# W와 b를 업데이트
	optimizer.step()

	# if epoch % 100 == 0:
	# # 100번마다 로그 출력
	print('Epoch {:4d}/{} Cost: {:.6f}'.format(
		epoch, nb_epochs, cost.item()
	  ))



Epoch    0/30 Cost: 31667.597656
Epoch    1/30 Cost: 9926.265625
Epoch    2/30 Cost: 3111.513184
Epoch    3/30 Cost: 975.451477
Epoch    4/30 Cost: 305.908539
Epoch    5/30 Cost: 96.042496
Epoch    6/30 Cost: 30.260748
Epoch    7/30 Cost: 9.641701
Epoch    8/30 Cost: 3.178671
Epoch    9/30 Cost: 1.152871
Epoch   10/30 Cost: 0.517863
Epoch   11/30 Cost: 0.318801
Epoch   12/30 Cost: 0.256388
Epoch   13/30 Cost: 0.236821
Epoch   14/30 Cost: 0.230660
Epoch   15/30 Cost: 0.228719
Epoch   16/30 Cost: 0.228095
Epoch   17/30 Cost: 0.227880
Epoch   18/30 Cost: 0.227799
Epoch   19/30 Cost: 0.227762
Epoch   20/30 Cost: 0.227732
Epoch   21/30 Cost: 0.227710
Epoch   22/30 Cost: 0.227680
Epoch   23/30 Cost: 0.227666
Epoch   24/30 Cost: 0.227646
Epoch   25/30 Cost: 0.227620
Epoch   26/30 Cost: 0.227597
Epoch   27/30 Cost: 0.227574
Epoch   28/30 Cost: 0.227553
Epoch   29/30 Cost: 0.227529
Epoch   30/30 Cost: 0.227505
Epoch   31/30 Cost: 0.227486
Epoch   32/30 Cost: 0.227468
Epoch   33/30 Cost: 0.22744

# Subclass 모델

In [39]:
model = nn.Linear(1,1)

In [40]:
class LinearRegressionModel(nn.Module):
	def __init__(self):
		super().__init__()
		self.linear1 = nn.Linear(3, 6)
		self.linear2 = nn.Linear(6, 3)
		self.linear3 = nn.Linear(3, 1)
		self.relu = nn.ReLU()
	
	def forward(self, x):
		x = self.linear1(x)
		x = self.relu(x)
		x = self.linear2(x)
		x = self.relu(x)
		x = self.linear3(x)

		return x

In [41]:
model = LinearRegressionModel()

In [42]:
optimizer = optim.Adam(model.parameters(), lr=1e-1)

epochs = 1000

for epoch in range(epochs):

	# H(x) 계산
	prediction = model(x_train)
	# model(x_train)은 model.forward(x_train)와 동일함.

	# cost 계산
	cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

	# cost로 H(x) 개선하는 부분
	# gradient를 0으로 초기화
	optimizer.zero_grad()
	# 비용 함수를 미분하여 gradient 계산
	cost.backward()
	# W와 b를 업데이트
	optimizer.step()

	# if epoch % 100 == 0:
	# # 100번마다 로그 출력
	print('Epoch {:4d}/{} Cost: {:.6f}'.format(
		epoch, nb_epochs, cost.item()
	  ))



Epoch    0/30 Cost: 27123.453125
Epoch    1/30 Cost: 22235.480469
Epoch    2/30 Cost: 15216.559570
Epoch    3/30 Cost: 7072.575684
Epoch    4/30 Cost: 763.970581
Epoch    5/30 Cost: 2062.238281
Epoch    6/30 Cost: 7513.181152
Epoch    7/30 Cost: 5887.244141
Epoch    8/30 Cost: 2085.907471
Epoch    9/30 Cost: 113.675697
Epoch   10/30 Cost: 371.405853
Epoch   11/30 Cost: 1611.809814
Epoch   12/30 Cost: 2725.224609
Epoch   13/30 Cost: 3211.925781
Epoch   14/30 Cost: 2995.195801
Epoch   15/30 Cost: 2225.776611
Epoch   16/30 Cost: 1201.609009
Epoch   17/30 Cost: 326.914398
Epoch   18/30 Cost: 2.944823
Epoch   19/30 Cost: 377.446503
Epoch   20/30 Cost: 1091.085938
Epoch   21/30 Cost: 1468.674316
Epoch   22/30 Cost: 1189.778809
Epoch   23/30 Cost: 563.700623
Epoch   24/30 Cost: 94.858597
Epoch   25/30 Cost: 20.146202
Epoch   26/30 Cost: 245.359833
Epoch   27/30 Cost: 535.448242
Epoch   28/30 Cost: 696.227966
Epoch   29/30 Cost: 650.551880
Epoch   30/30 Cost: 438.180267
Epoch   31/30 Cost: 179

# Dataset & DataLoader

In [43]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

from torch.utils.data import TensorDataset, Dataset, DataLoader

In [44]:
dataset = TensorDataset(x_train, y_train)

In [45]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [46]:
for i, data in enumerate(dataloader):
	print(i, data)

0 [tensor([[ 73.,  66.,  70.],
        [ 96.,  98., 100.]]), tensor([[142.],
        [196.]])]
1 [tensor([[73., 80., 75.],
        [93., 88., 93.]]), tensor([[152.],
        [185.]])]
2 [tensor([[89., 91., 90.]]), tensor([[180.]])]


In [47]:
class LinearRegressionModel(nn.Module):
	def __init__(self):
		super().__init__()
		self.linear1 = nn.Linear(3, 6) # bias=False로 설정 가능
		self.linear2 = nn.Linear(6, 3)
		self.linear3 = nn.Linear(3, 1)
		self.relu = nn.ReLU()
	
	def forward(self, x):
		x = self.linear1(x)
		x = self.relu(x)
		x = self.linear2(x)
		x = self.relu(x)
		x = self.linear3(x)

		return x

model = LinearRegressionModel()
print(model)

LinearRegressionModel(
  (linear1): Linear(in_features=3, out_features=6, bias=True)
  (linear2): Linear(in_features=6, out_features=3, bias=True)
  (linear3): Linear(in_features=3, out_features=1, bias=True)
  (relu): ReLU()
)


In [49]:
optimizer = optim.Adam(model.parameters(), lr=5e-1)

epochs = 1000

for epoch in range(epochs+1):
	for idx, batch in enumerate(dataloader):
		x, y_true = batch

		y_pred = model(x)

		loss = F.mse_loss(y_pred, y_true)

		optimizer.zero_grad()
		loss.backward()
		optimizer.step()

		if epoch % 50 == 0:
			print('Epoch {:4d}/{} Batch {}/{} Loss: {:.6f}'.format(epoch, epochs, idx, len(dataloader), loss.item()))

Epoch    0/1000 Batch 0/3 Loss: 25308.191406
Epoch    0/1000 Batch 1/3 Loss: 90.276077
Epoch    0/1000 Batch 2/3 Loss: 209751.750000
Epoch   50/1000 Batch 0/3 Loss: 10444.890625
Epoch   50/1000 Batch 1/3 Loss: 16808.371094
Epoch   50/1000 Batch 2/3 Loss: 8214.852539
Epoch  100/1000 Batch 0/3 Loss: 5166.576172
Epoch  100/1000 Batch 1/3 Loss: 4099.434570
Epoch  100/1000 Batch 2/3 Loss: 1662.861450
Epoch  150/1000 Batch 0/3 Loss: 1426.677734
Epoch  150/1000 Batch 1/3 Loss: 1586.862061
Epoch  150/1000 Batch 2/3 Loss: 82.719604
Epoch  200/1000 Batch 0/3 Loss: 480.221802
Epoch  200/1000 Batch 1/3 Loss: 240.704498
Epoch  200/1000 Batch 2/3 Loss: 1342.057983
Epoch  250/1000 Batch 0/3 Loss: 396.086304
Epoch  250/1000 Batch 1/3 Loss: 584.896484
Epoch  250/1000 Batch 2/3 Loss: 224.670532
Epoch  300/1000 Batch 0/3 Loss: 273.377747
Epoch  300/1000 Batch 1/3 Loss: 434.462006
Epoch  300/1000 Batch 2/3 Loss: 698.428345
Epoch  350/1000 Batch 0/3 Loss: 456.259857
Epoch  350/1000 Batch 1/3 Loss: 277.3865

# Custom Dataset

In [160]:
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [161]:
# Dataset 상속
class CustomDataset(Dataset): 
  def __init__(self):
    self.x_data = [[73, 80, 75],
                   [93, 88, 93],
                   [89, 91, 90],
                   [96, 98, 100],
                   [73, 66, 70]]
    self.y_data = [[152], [185], [180], [196], [142]]

  # 총 데이터의 개수를 리턴
  def __len__(self): 
    return len(self.x_data)

  # 인덱스를 입력받아 그에 맵핑되는 입출력 데이터를 파이토치의 Tensor 형태로 리턴
  def __getitem__(self, idx): 
    x = torch.FloatTensor(self.x_data[idx])
    y = torch.FloatTensor(self.y_data[idx])
    return x, y


In [162]:
dataset = CustomDataset()

In [164]:
dataset.__len__()

5

In [167]:
dataset.__getitem__(0)

(tensor([73., 80., 75.]), tensor([152.]))

In [168]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [170]:
model = LinearRegressionModel()
optimizer = optim.Adam(model.parameters(), lr=5e-1)

epochs = 1000

for epoch in range(epochs+1):
	for idx, batch in enumerate(dataloader):
		x, y_true = batch

		y_pred = model(x)

		loss = F.mse_loss(y_pred, y_true)

		optimzizer.zero_grad()
		loss.backward()
		optimizer.step()

		if epoch % 50 == 0:
			print('Epoch {:4d}/{} Batch {}/{} Loss: {:.6f}'.format(epoch, idx, len(dataloader), epochs, loss.item()))

Epoch    0/0 Batch 3/1000 Loss: 35371.648438
Epoch    0/1 Batch 3/1000 Loss: 3645.324219
Epoch    0/2 Batch 3/1000 Loss: 39348.425781
Epoch   50/0 Batch 3/1000 Loss: 7674.965820
Epoch   50/1 Batch 3/1000 Loss: 5383.468750
Epoch   50/2 Batch 3/1000 Loss: 8824.833984
Epoch  100/0 Batch 3/1000 Loss: 1884.051514
Epoch  100/1 Batch 3/1000 Loss: 2352.415283
Epoch  100/2 Batch 3/1000 Loss: 896.020935
Epoch  150/0 Batch 3/1000 Loss: 12562.760742
Epoch  150/1 Batch 3/1000 Loss: 10898.626953
Epoch  150/2 Batch 3/1000 Loss: 5730.796875
Epoch  200/0 Batch 3/1000 Loss: 2221.288330
Epoch  200/1 Batch 3/1000 Loss: 4320.256836
Epoch  200/2 Batch 3/1000 Loss: 5819.720703
Epoch  250/0 Batch 3/1000 Loss: 2690.535156
Epoch  250/1 Batch 3/1000 Loss: 3419.103516
Epoch  250/2 Batch 3/1000 Loss: 814.977661
Epoch  300/0 Batch 3/1000 Loss: 14816.242188
Epoch  300/1 Batch 3/1000 Loss: 10681.101562
Epoch  300/2 Batch 3/1000 Loss: 5712.868164
Epoch  350/0 Batch 3/1000 Loss: 2487.576660
Epoch  350/1 Batch 3/1000 Lo

In [173]:
model = LinearRegressionModel()
optimizer = optim.Adam(model.parameters(), lr=5e-1)

epochs = 1000

for epoch in range(epochs+1):
	for idx, batch in enumerate(dataloader):
		x, y_true = batch

		y_pred = model(x)

		loss = F.mse_loss(y_pred, y_true)

		
		loss.backward()
		optimzizer.zero_grad()
		optimizer.step()

		if epoch % 50 == 0:
			print('Epoch {:4d}/{} Batch {}/{} Loss: {:.6f}'.format(epoch, epochs, idx+1, len(dataloader), loss.item()))

Epoch    0/1000 Batch 1/3 Loss: 28020.972656
Epoch    0/1000 Batch 2/3 Loss: 64575.546875
Epoch    0/1000 Batch 3/3 Loss: 6940.395508
Epoch   50/1000 Batch 1/3 Loss: 4183.465820
Epoch   50/1000 Batch 2/3 Loss: 7583.054688
Epoch   50/1000 Batch 3/3 Loss: 1418.866089
Epoch  100/1000 Batch 1/3 Loss: 514.882690
Epoch  100/1000 Batch 2/3 Loss: 2072.714355
Epoch  100/1000 Batch 3/3 Loss: 2944.064209
Epoch  150/1000 Batch 1/3 Loss: 8760.905273
Epoch  150/1000 Batch 2/3 Loss: 10963.647461
Epoch  150/1000 Batch 3/3 Loss: 18136.341797
Epoch  200/1000 Batch 1/3 Loss: 10078.388672
Epoch  200/1000 Batch 2/3 Loss: 12278.636719
Epoch  200/1000 Batch 3/3 Loss: 19695.853516
Epoch  250/1000 Batch 1/3 Loss: 2080.991699
Epoch  250/1000 Batch 2/3 Loss: 1724.023071
Epoch  250/1000 Batch 3/3 Loss: 376.734619
Epoch  300/1000 Batch 1/3 Loss: 5707.285645
Epoch  300/1000 Batch 2/3 Loss: 1671.268433
Epoch  300/1000 Batch 3/3 Loss: 8125.472656
Epoch  350/1000 Batch 1/3 Loss: 14163.880859
Epoch  350/1000 Batch 2/3 