벡터 $[0,1,2,3,4,5,6,7,8]$를 먼저 만들고 $3 \times 3$행렬로 reshape을 합니다.

In [5]:
import numpy as np

vec = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

vec = vec.reshape(3,3)
vec

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

$3 \times 3$ 행렬에 숫자 1을 더하라고 하면 numpy는 모든 항에 1을 더하라는 뜻으로 받아들입니다.

In [7]:
# 브로드캐스팅 이용

vec+1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

$3 \times 3$ 행렬에 행벡터 $[1,2,3]$을 더하라고 하면 numpy는 각 행에 행벡터 $[1,2,3]$을 더하라는 뜻으로 받아들입니다.

In [8]:
# 브로드캐스팅 이용
vec + [1, 2, 3]


array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

$3 \times 3$ 행렬에 열벡터 $\begin{bmatrix}1\\2\\3\end{bmatrix}$을 더하라고 하면 numpy는 각 열에 열벡터 $\begin{bmatrix}1\\2\\3\end{bmatrix}$을 더하라는 뜻으로 받아들입니다.

In [10]:
# 브로드캐스팅 이용

vec + np.array([1, 2, 3]).T

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

### mnist_show.py를 수정하여 2,3,4번째 변형된 이미지가 출력되도록 하시오.  

![image-4.png](attachment:image-4.png)

In [11]:
import sys
sys.path.append('C:/Users/user/Downloads/deep-learning-from-scratch-master/') # 각자의 경로로 수정해주세요.

컴퓨터가 이미지를 이해하는 방식은 행렬입니다.

In [ ]:
import numpy as np
from dataset.mnist import load_mnist

np.set_printoptions(linewidth=200,threshold=1000)

(x_train, t_train), (x_test, t_test) = load_mnist(flatten=False, normalize=False)

x = x_train[0][0]

print(x)

행렬의 항들은 픽셀의 밝기를 나타냅니다.  
$255 - [x_{i,j}]$은 스칼라 빼기 행렬이라서 수학에서는 잘못된 표현이지만 파이썬은 $[255 - x_{i,j}]$로 이해합니다.  
어두운 픽셀은 밝아지고 밝은 픽셀은 어두워집니다.

이미지를 대각선으로 뒤집는 변환은 선형대수학 관점에서는 transpose입니다.

$128 - [x_{i,j}]$은 스칼라 빼기 행렬이라서 수학에서는 잘못된 표현이지만 파이썬은 $[128 - x_{i,j}]$로 이해합니다.  
255를 넘어가거나 0보다 작게 되면 시계방식 (modulo 방식)으로 0부터 255로 맞춰줍니다.  
어두운 픽셀과 밝은 픽셀은 1회색이 됩니다.  
회색 픽셀은 128보다 좀 작으면 어두운 색으로 128보다 좀 크면 밝은색이 됩니다.

28×28 해상도의 검정 사진을 먼저 만든후 i열에 원본 이미지의 오른쪽으로부터 세서 i열을 복사합니다.  
결과적으로 좌우 반전 시킨 행렬이 됩니다.

In [ ]:
x1 = np.zeros((28,28), dtype=int)
for i in range(28):
    x1[:,i] =
print(x1)

28×28 해상도의 검정 사진을 먼저 만든후 i행에 원본 이미지의 아래로부터 세서 i행을 복사합니다.  
결과적으로 상하 반전 시킨 행렬이 됩니다.

In [ ]:
x2 = np.zeros((28,28), dtype=int)
for i in range(28):
    x2[i,:] =
print(x2)

따라서, 마지막 줄 코드 img_show(img)를 간단히 img_show(255 - img)와 img_show(img.T)로 수정해주면 두번째와 세번째 이미지를 각각 얻을수 있습니다.

주피터 노트북에서 이미지를 출력하기 위해서 PIL 라이브러리 대신 plt.imshow를 사용하겠습니다.

In [ ]:
import matplotlib.pyplot as plt

x = x_train[0][0]

plt.imshow(x, cmap=plt.cm.gray)
plt.xticks([])
plt.yticks([])
plt.show()

plt.imshow(255 - x, cmap=plt.cm.gray)
plt.xticks([])
plt.yticks([])
plt.show()

plt.imshow(x.T, cmap=plt.cm.gray)
plt.xticks([])
plt.yticks([])
plt.show()

plt.imshow(128 - x, cmap=plt.cm.gray)
plt.xticks([])
plt.yticks([])
plt.show()

x1 = np.zeros((28,28), dtype=int)
for i in range(28):
    x1[:,i] = x[:,27-i]
plt.imshow(x1, cmap=plt.cm.gray)
plt.xticks([])
plt.yticks([])
plt.show()

x2 = np.zeros((28,28), dtype=int)
for i in range(28):
    x2[i,:] = x[27-i,:]
plt.imshow(x2, cmap=plt.cm.gray)
plt.xticks([])
plt.yticks([])
plt.show()

### 적절한 5 X 5 행렬에 `plt.imshow`를 적용하여 다음 여섯 이미지를 출력하시오. (cmap=plt.cm.gray)
![image.png](attachment:image.png)

작은 사각형 하나 하나가 픽셀입니다. $5 \times 5$ 해상도 이미지네요.
밝기의 패턴을 보고 $5 \times 5$ 행렬을 만듭니다.

In [ ]:
x =

plt.imshow를 이용해 행렬을 이미지로 변환합니다.

In [ ]:
plt.imshow(x,cmap=plt.cm.gray)
plt.xticks([])
plt.yticks([])
plt.show()

transpose를 합니다.

In [ ]:
plt.imshow(x.T,cmap=plt.cm.gray)
plt.xticks([])
plt.yticks([])
plt.show()

밝은 픽셀은 어둡게 어두운 픽셀은 밝게 뒤집습니다.
최대 밝기가 24이므로 24에서 빼주면 대소관계가 뒤집힙니다.
행렬로 쓸필요 없이 숫자 24에서 빼면 파이썬이 브로드케스팅으로 처리합니다.

In [ ]:
plt.imshow(24-x,cmap=plt.cm.gray)
plt.xticks([])
plt.yticks([])
plt.show()

중앙행만 1이고 나머지는 0인 행렬을 만듭니다.
파이썬은 0부터 출발하기 때문에 2행이 중앙행입니다.

In [ ]:
x1=np.zeros((5,5))
x1[2,:]=1
print(x)

In [ ]:
plt.imshow(x1,cmap=plt.cm.gray)
plt.xticks([])
plt.yticks([])
plt.show()

중앙열만 1이고 나머지는 0인 행렬을 만듭니다. 파이썬은 0부터 출발하기 때문에 2열이 중앙열입니다.

In [ ]:
x2=np.zeros((5,5))
x2[:,2]=1
print(x2)

In [ ]:
plt.imshow(x2,cmap=plt.cm.gray)
plt.xticks([])
plt.yticks([])
plt.show()

두 행렬을 더합니다.

In [ ]:
print(x1+x2)

plt.imshow(x1+x2,cmap=plt.cm.gray)
plt.xticks([])
plt.yticks([])
plt.show()

####  훈련데이터의 라벨별 데이터 개수를 출력하는 코드

In [ ]:
for i in range(10):
    print(str(i)+'의 개수 : ' + str(np.sum(t_train==i)))

### MNIST imshow.py를 수정하여 훈련용 MNIST데이터중 라벨이 2인 데이터 첫 25개를 다음과 같이 출력하시오.
![image.png](attachment:image.png)

라벨이 2인 인덱스를 모은 리스트를 먼저 만듭니다.

In [ ]:
N=2
N_index=[]

for k in range(len(x_train)):
    if t_train[k]==N:
        N_index.append(k)

print(N_index)

In [ ]:
plt.figure(figsize=(10,10))

for i in range(25):
    plt.subplot(5,5,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.imshow(x_train[N_index[i]][0], cmap=plt.cm.binary)

plt.show()

### MNIST_imshow.py를 수정하여 훈련용 MNIST데이터중 랜덤하게 25개를 뽑아서 5 X5 모아찍기로 출력하시오.

`np.random.choice`를 이용해 인덱스 $0,1,2,\cdots, 59999$w중에서 25개의 숫자를 랜덤하게 뽑습니다.  
랜덤하게 뽑으므로 실행할때마다 뽑히는 인덱스는 달라집니다.

In [ ]:
random_index = np.random.choice(len(x_train), 25)
print(random_index)

In [ ]:
plt.figure(figsize=(10,10))

for i in range(25):
    plt.subplot(5,5,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.imshow(x_train[random_index[i]][0], cmap=plt.cm.binary)

plt.show()